# 데이터 기술 통계량 확인 

- 연속형 : 대표값 (평균/중앙값) / 산포 (표준편차)
- 범주형 : 항목 빈도수

In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv('01_Data.csv')

In [6]:
df1['Amount_Month'].mean( ) # 평균

93994.97428900021

In [7]:
df1['Amount_Month'].median() # 중앙값

96900.0

In [9]:
df1['Amount_Month'].std() # 표준편차

15304.263988475595

In [10]:
df1['Amount_Month'].max() # 최대값

215700

In [11]:
df1['Amount_Month'].min() # 최소값

54603

In [12]:
df1.describe() # 해당 데이터의 모든 숫자 데이터의 요약통계량 확인

# 50% : 중앙값을 알려줌 
# 이 요약통계량이 차트형태로 나왔다는 것은 엑셀로도 저장이 가능함을 의미함

,Index,Member_ID,Term,Amount_Month,Age,Overdue_count,Credit_Rank
count,51301.000000,5.130100e+04,51301.000000,51301.000000,44329.000000,51301.000000,42520.000000
mean,25651.703612,6.266432e+07,55.639149,93994.974289,50.024093,0.161381,3.428810
std,14809.828628,1.216146e+07,12.009915,15304.263988,10.983877,1.122193,2.213453
min,1.000000,2.568798e+07,12.000000,54603.000000,25.000000,0.000000,0.000000
25%,12826.000000,6.643148e+07,60.000000,81900.000000,42.000000,0.000000,1.000000
50%,25652.000000,6.676578e+07,60.000000,96900.000000,49.000000,0.000000,3.000000
75%,38477.000000,6.678160e+07,60.000000,98400.000000,57.000000,0.000000,5.000000
max,51302.000000,6.696986e+07,60.000000,215700.000000,102.000000,15.000000,10.000000

In [14]:
# 요약통계량 표를 엑셀로 저장
df1.describe().to_excel('describe_result.xlsx')

In [4]:
# 문자데이터 항목 확인 (인자 확인)
df1['Channel'].unique()

array(['영업방판', '홈쇼핑/방송', '재계약', '전문매장H', '전문매장Z', '대형마트H', '대형마트E',
       '홈쇼핑/인터넷', '전단홍보', '직영유통사', '대형마트A', '대형마트N', '대형마트C', '직영계열사B',
       '자체홈페이지', '직영계열사A'], dtype=object)

In [5]:
# 문자 데이터 빈도수 확인

In [6]:
df1['Channel'].value_counts()

Channel
영업방판       23767
홈쇼핑/방송     12977
대형마트A       4725
전문매장H       3227
재계약         2193
대형마트E       1497
전문매장Z       1206
전단홍보         560
홈쇼핑/인터넷      375
대형마트H        225
직영유통사        188
자체홈페이지       120
대형마트C        119
대형마트N         83
직영계열사A        20
직영계열사B        19
Name: count, dtype: int64

In [9]:
# 문자데이터('Object')의 요약통계량 확인
df1.describe(include='object')
# unique : 항목 수를 의미함 / top : 최빈값, 가장 빈도수가 높은 항목을 알려줌 / freq : 최빈값의 개수를 알려줌

,Sales_Type,Contract_Type,Channel,Datetime,Payment_Type,Product_Type,Customer_Type,Address1,Address2,State,Overdue_Type,Gender,Bank
count,51301,51301,51301,51301,51301,51301,51299,51299,51299,51301,51301,51301,48542
unique,2,9,16,577,5,6,2,8,14,4,2,2,47
top,렌탈,프로모션계약,영업방판,2019-01-31,CMS,DES-1,개인,경기도,경기도,계약확정,없음,여자,롯데카드
freq,46483,15811,23767,1167,32825,39133,46263,18353,14883,50620,49110,35602,9516

In [11]:
# 문자 / 숫자 요약 통계량 확인 -> 엑셀로 저장가능
df1.describe(include='all').to_excel('describe_result_all.xlsx')

 - 데이터 층별화

In [12]:
df1['Amount_Month'].mean()

93994.97428900021

In [13]:
# 제품군('Product_Type') 별로 월랜탈비용('Amount_Month')의 평균을 확인
df1.pivot_table(index='Product_Type', values='Amount_Month', aggfunc='mean')

               Amount_Month
Product_Type
DES-1          94424.545166
DES-2          87556.390618
DES-3A         94706.900529
DES-R4        129444.954128
ERA           119744.720497
MMC           189450.000000

In [14]:
# 제품군('Product_Type') 별로 월랜탈비용('Amount_Month')의 평균과 합을 확인
df1.pivot_table(index='Product_Type', values='Amount_Month', aggfunc=['mean', 'sum'])

                       mean          sum
               Amount_Month Amount_Month
Product_Type
DES-1          94424.545166   3695115726
DES-2          87556.390618    787657290
DES-3A         94706.900529    197085060
DES-R4        129444.954128     42328500
ERA           119744.720497     77115600
MMC           189450.000000     22734000

In [15]:
# 제품군('Product_Type') 별로 월랜탈비용('Amount_Month')과 계약기간(Term)의 평균을 확인
df1.pivot_table(index='Product_Type', values=['Amount_Month','Term'], aggfunc='mean')

               Amount_Month       Term
Product_Type
DES-1          94424.545166  55.408274
DES-2          87556.390618  57.014673
DES-3A         94706.900529  59.619414
DES-R4        129444.954128  58.972477
ERA           119744.720497  39.000000
MMC           189450.000000  39.000000

In [16]:
# 제품군('Product_Type')과 계약유형(Sales_Type) 별로 월랜탈비용('Amount_Month')과 계약기간(Term)의 평균을 확인
df1.pivot_table(index=['Product_Type', 'Sales_Type'], 
                values=['Amount_Month','Term'], aggfunc='mean')

                          Amount_Month       Term
Product_Type Sales_Type
DES-1        렌탈           98694.923613  59.838978
             멤버십          63161.706570  22.971720
DES-2        렌탈           87901.899247  57.503655
             멤버십          57725.242718  14.796117
DES-3A       렌탈           94752.196532  59.676301
             멤버십          75900.000000  36.000000
DES-R4       렌탈          130616.250000  60.000000
             멤버십          75900.000000  12.000000
ERA          렌탈          119744.720497  39.000000
MMC          렌탈          189450.000000  39.000000

In [18]:
# 제품군('Product_Type') 별로 월랜탈비용('Amount_Month')의 합을 확인, 열을 계약유형(Sales_Type)별로 정리
df1.pivot_table(index='Product_Type', values='Amount_Month', 
                aggfunc='sum', columns='Sales_Type')

Sales_Type              렌탈          멤버십
Product_Type
DES-1         3.398066e+09  297049506.0
DES-2         7.817116e+08    5945700.0
DES-3A        1.967056e+08     379500.0
DES-R4        4.179720e+07     531300.0
ERA           7.711560e+07          NaN
MMC           2.273400e+07          NaN

In [19]:
df1.pivot_table(index='Product_Type', values='Amount_Month', 
                aggfunc='sum', columns='Sales_Type', fill_value=0)
# fill_value : pivot.table 계산을 통해 발생한 결측값에 원하는 값을 입력

Sales_Type            렌탈        멤버십
Product_Type
DES-1         3398066220  297049506
DES-2          781711590    5945700
DES-3A         196705560     379500
DES-R4          41797200     531300
ERA             77115600          0
MMC             22734000          0

In [5]:
# 날짜 데이터 변환 
df1['Datetime_dt'] = pd.to_datetime(df1['Datetime'])  # -> 이렇게 한다고 해서 df1에 Datetime이 바로 덮어서 전환되는 것은 아니다. 
# Datetime 데이터를 날짜형식의 데이터로 변환하여 df1 데이터 프레임에 새로운 Datetime_dt 변수로 선언함

In [6]:
df1['Year'] = df1['Datetime_dt'].dt.year    # 날짜형식의 데이터에서 연도 추출 
df1['Month'] = df1['Datetime_dt'].dt.month  # 월 추출
df1['Day'] = df1['Datetime_dt'].dt.day      # 일 추출 
df1['Day_of_week'] = df1['Datetime_dt'].dt.day_name()   # 요일 추출
df1['Week'] = df1['Datetime_dt'].dt.isocalendar().week  # 주차 추출

In [7]:
df1

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,...,Overdue_Type,Gender,Credit_Rank,Bank,Datetime_dt,Year,Month,Day,Day_of_week,Week
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,...,없음,여자,9.0,새마을금고,2019-05-06,2019,5,6,Monday,19
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,...,없음,남자,2.0,현대카드,2020-02-20,2020,2,20,Thursday,8
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,...,없음,여자,8.0,우리은행,2019-02-28,2019,2,28,Thursday,9
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,...,없음,남자,5.0,농협회원조합,2019-05-13,2019,5,13,Monday,20
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,...,있음,남자,8.0,농협회원조합,2019-05-10,2019,5,10,Friday,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,...,없음,남자,NaN,기업은행,2019-03-01,2019,3,1,Friday,9
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,...,없음,여자,8.0,새마을금고,2019-04-01,2019,4,1,Monday,14
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,...,없음,여자,1.0,롯데카드,2019-04-01,2019,4,1,Monday,14
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,...,없음,여자,2.0,롯데카드,2020-02-06,2020,2,6,Thursday,6
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,...,없음,여자,8.0,신한은행,2019-04-24,2019,4,24,Wednesday,17

In [8]:
# 연도 별, 제품군 별 월랜탈비용의 합을 계산하여 데이터파일로 저장
df1.pivot_table(index='Product_Type', values='Amount_Month', 
               columns= 'Year', aggfunc='sum')

Year                2019       2020
Product_Type
DES-1         2946278610  748837116
DES-2          631877970  155779320
DES-3A         157162560   39922500
DES-R4          33891300    8437200
ERA             62944500   14171100
MMC             17540100    5193900

In [36]:
# 파생 변수 생성
# 월랜탈비용(Amount_Month)와 계약기간(Term)을 곱하여, 총계약금액(Total_Amount)을 계산
df1['Total_Amount'] = df1['Amount_Month'] * df1['Term']

In [37]:
df1

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,...,Gender,Credit_Rank,Bank,Datetime_dt,Year,Month,Day,Day_of_week,Week,Total_Amount
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,...,여자,9.0,새마을금고,2019-05-06,2019,5,6,Monday,19,5814000
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,...,남자,2.0,현대카드,2020-02-20,2020,2,20,Thursday,8,6174000
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,...,여자,8.0,우리은행,2019-02-28,2019,2,28,Thursday,9,5814000
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,...,남자,5.0,농협회원조합,2019-05-13,2019,5,13,Monday,20,802800
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,...,남자,8.0,농협회원조합,2019-05-10,2019,5,10,Friday,19,802800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,...,남자,NaN,기업은행,2019-03-01,2019,3,1,Friday,9,5814000
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,...,여자,8.0,새마을금고,2019-04-01,2019,4,1,Monday,14,5814000
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,...,여자,1.0,롯데카드,2019-04-01,2019,4,1,Monday,14,4715100
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,...,여자,2.0,롯데카드,2020-02-06,2020,2,6,Thursday,6,5814000
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,...,여자,8.0,신한은행,2019-04-24,2019,4,24,Wednesday,17,5814000

In [45]:
# 비교구문과 loc함수를 활용해 데이터를 그룹화 ex) 40대 이상은 40대, 80대 이상은 80대로 묶기 
cond1 = (df1['Age']>=70)
cond2 = (df1['Age']>=60)
cond3 = (df1['Age']>=50)
cond4 = (df1['Age']>=40)
cond5 = (df1['Age'] < 40)

df1.loc[cond5, '연령대'] = '30대이하'
df1.loc[cond4, '연령대'] = '40대'
df1.loc[cond3, '연령대'] = '50대'
df1.loc[cond2, '연령대'] = '60대'
df1.loc[cond1, '연령대'] = '70대이상'

In [43]:
df1

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,...,Credit_Rank,Bank,Datetime_dt,Year,Month,Day,Day_of_week,Week,Total_Amount,연령대
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,...,9.0,새마을금고,2019-05-06,2019,5,6,Monday,19,5814000,NaN
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,...,2.0,현대카드,2020-02-20,2020,2,20,Thursday,8,6174000,NaN
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,...,8.0,우리은행,2019-02-28,2019,2,28,Thursday,9,5814000,NaN
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,...,5.0,농협회원조합,2019-05-13,2019,5,13,Monday,20,802800,NaN
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,...,8.0,농협회원조합,2019-05-10,2019,5,10,Friday,19,802800,60대
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,...,NaN,기업은행,2019-03-01,2019,3,1,Friday,9,5814000,NaN
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,...,8.0,새마을금고,2019-04-01,2019,4,1,Monday,14,5814000,NaN
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,...,1.0,롯데카드,2019-04-01,2019,4,1,Monday,14,4715100,60대
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,...,2.0,롯데카드,2020-02-06,2020,2,6,Thursday,6,5814000,NaN
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,...,8.0,신한은행,2019-04-24,2019,4,24,Wednesday,17,5814000,NaN

In [46]:
df1['연령대'].value_counts()

연령대
40대      16283
50대      12522
30대이하     7205
60대       5947
70대이상     2372
Name: count, dtype: int64

In [51]:
# apply( ) : 파이썬 함수의 개념을 활용해 데이터를 처리
def func1(x):
    if x >= 70 : 
        return '70대이상'
    elif x >= 60 : 
        return '60대'
    elif x >=  50 : 
        return '50대'
    else: 
        return '40대이하'


df1['Age'].apply(func1)

0        40대이하
1        40대이하
2        40대이하
3        40대이하
4          60대
         ...
51296    40대이하
51297    40대이하
51298      60대
51299      50대
51300      50대
Name: Age, Length: 51301, dtype: object

In [50]:
func1(400)

500

In [58]:
def func2(x):
    return str(x)[0] + '0대'        # str() : 숫자 데이터를 문자데이터로 전환시켜준다


df1['연령대'] = df1['Age'].apply(func2)

In [56]:
str1 = 'Python'
str1[0] # [] : 특정 문자열 데이터의 특정 위치의 글자를 찾을 때 사용한다.

'P'

In [59]:
df1

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,...,Credit_Rank,Bank,Datetime_dt,Year,Month,Day,Day_of_week,Week,Total_Amount,연령대
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,...,9.0,새마을금고,2019-05-06,2019,5,6,Monday,19,5814000,40대
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,...,2.0,현대카드,2020-02-20,2020,2,20,Thursday,8,6174000,30대
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,...,8.0,우리은행,2019-02-28,2019,2,28,Thursday,9,5814000,40대
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,...,5.0,농협회원조합,2019-05-13,2019,5,13,Monday,20,802800,30대
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,...,8.0,농협회원조합,2019-05-10,2019,5,10,Friday,19,802800,60대
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,...,NaN,기업은행,2019-03-01,2019,3,1,Friday,9,5814000,40대
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,...,8.0,새마을금고,2019-04-01,2019,4,1,Monday,14,5814000,40대
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,...,1.0,롯데카드,2019-04-01,2019,4,1,Monday,14,4715100,60대
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,...,2.0,롯데카드,2020-02-06,2020,2,6,Thursday,6,5814000,50대
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,...,8.0,신한은행,2019-04-24,2019,4,24,Wednesday,17,5814000,50대

In [60]:
df1['연령대'].value_counts()

연령대
40대    16283
50대    12522
n0대     6972
30대     6798
60대     5947
70대     1737
80대      576
20대      407
90대       57
10대        2
Name: count, dtype: int64

 - 결측값 확인 및 처리 (Missing Value => NaN (Not A Number))
 
 - 결측값 제거 : 결측값이 존재하는 행을 제거 (보통 가장 많이 쓴다 / 결측치를 대치해서 어떤 수를 집어넣는다면 전체 데이터의
                 왜곡이 심해지기 때문이다)
 - 결측값 대치 : 결측값을 다른 값으로 채워넣는 방법 (결측치의 개수가 너무 많다면, 대치를 함)
    - 단순대치 
    - 알고리즘 대치 : 머신러닝 기법 중 하나, 주변 값과 유사한 값을 이용해 대치를 함 
    - 보간법 : ex) 공장에서 품질 데이터 - 4시간, 공정 데이터 - 10분 단위 추출 // -> 그 사이에 있는 데이터의 개수만큼 데이터의 간격을 
               나눠서 대치하는 방법

In [3]:
# 결측값 확인 
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51301 entries, 0 to 51300
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          51301 non-null  int64
 1   Member_ID      51301 non-null  int64
 2   Sales_Type     51301 non-null  object
 3   Contract_Type  51301 non-null  object
 4   Channel        51301 non-null  object
 5   Datetime       51301 non-null  object
 6   Term           51301 non-null  int64
 7   Payment_Type   51301 non-null  object
 8   Product_Type   51301 non-null  object
 9   Amount_Month   51301 non-null  int64
 10  Customer_Type  51299 non-null  object
 11  Age            44329 non-null  float64
 12  Address1       51299 non-null  object
 13  Address2       51299 non-null  object
 14  State          51301 non-null  object
 15  Overdue_count  51301 non-null  int64
 16  Overdue_Type   51301 non-null  object
 17  Gender         51301 non-null  object
 18  Credit_Rank    42520 non-null  float64
 19  Bank           48542 non-null  object
dtypes: float64(2), int64(5), object(13)
memory usage: 7.8+ MB

In [4]:
df1.isnull()

# isnull() : 해당 데이터가 결측값인지 아닌지를 판별하는 함수

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
51297,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
51298,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
51299,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
51300,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
# 각 항목별 결측값의 개수를 확인해주는 코드 

df1.isnull().sum()

Index               0
Member_ID           0
Sales_Type          0
Contract_Type       0
Channel             0
Datetime            0
Term                0
Payment_Type        0
Product_Type        0
Amount_Month        0
Customer_Type       2
Age              6972
Address1            2
Address2            2
State               0
Overdue_count       0
Overdue_Type        0
Gender              0
Credit_Rank      8781
Bank             2759
dtype: int64

In [7]:
# 결측값 제거 -> 이 결측값을 제거한 결과를 사용하기 위해서는 데이터 테이블을 새로운 변수(df1_clean / 파생 데이터 프레임)로 선언해야함!
df1_clean = df1. dropna()
df1_clean

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51295,51297,66792261,렌탈,일반계약,홈쇼핑/방송,2019-03-11,60,카드이체,DES-1,96900,개인,45.0,경기도,경기도,계약확정,0,없음,여자,1.0,롯데카드
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행

In [8]:
df1_clean.isnull().sum()

Index            0
Member_ID        0
Sales_Type       0
Contract_Type    0
Channel          0
Datetime         0
Term             0
Payment_Type     0
Product_Type     0
Amount_Month     0
Customer_Type    0
Age              0
Address1         0
Address2         0
State            0
Overdue_count    0
Overdue_Type     0
Gender           0
Credit_Rank      0
Bank             0
dtype: int64

In [14]:
# 특정 항목 (Column)을 제외한 뒤, 결측값을 제거 
df1_clean2 = df1.drop(columns=['Credit_Rank','Age']).dropna()
# 결측값 항목이 많은 'Credit_Rank','Age' 항목을 제외한 뒤 -> 데이터가 단순 결측값을 제거한 뒤보다 더 많이 살아남음
df1_clean2

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,경기도,경기도,계약확정,0,없음,여자,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,경기도,경기도,계약확정,0,없음,남자,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,경기도,경기도,계약확정,0,없음,여자,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,경기도,경기도,계약확정,0,없음,남자,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,경기도,경기도,기간만료,12,있음,남자,농협회원조합
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,경기도,경기도,계약확정,0,없음,남자,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,경기도,경기도,계약확정,0,없음,여자,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,서울특별시,서울특별시,계약확정,0,없음,여자,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,서울특별시,서울특별시,계약확정,0,없음,여자,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,서울특별시,서울특별시,계약확정,0,없음,여자,신한은행

 # 결측치를 나타내는 값
 
 - NaN (Not A Number)
 - NA  (Not Available)
 - None
 - Null
 - inf
 ...

In [17]:
# 결측값 대치 (단순대치) / fillna() : 특정 값으로 결측값을 대치
df1['Credit_Rank_clean1'] = df1['Credit_Rank'].fillna(0)
df1['Credit_Rank_clean1']

0        9.0
1        2.0
2        8.0
3        5.0
4        8.0
        ...
51296    0.0
51297    8.0
51298    1.0
51299    2.0
51300    8.0
Name: Credit_Rank_clean1, Length: 51301, dtype: float64

In [19]:
# 결측값에 평균 대치 (단순대치)
df1['Credit_Rank'].fillna( df1['Credit_Rank'].mean() )

0        9.00000
1        2.00000
2        8.00000
3        5.00000
4        8.00000
          ...
51296    3.42881
51297    8.00000
51298    1.00000
51299    2.00000
51300    8.00000
Name: Credit_Rank, Length: 51301, dtype: float64

In [20]:
# 결측값에 중앙값 대치 (단순대치)
df1['Credit_Rank'].fillna( df1['Credit_Rank'].median() )

0        9.0
1        2.0
2        8.0
3        5.0
4        8.0
        ...
51296    3.0
51297    8.0
51298    1.0
51299    2.0
51300    8.0
Name: Credit_Rank, Length: 51301, dtype: float64