In [1]:
import pandas as pd

In [2]:
two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], 
                       ['yoonsoo', 88, 75]]

In [5]:
my_df = pd.DataFrame(two_dimensional_list, columns=['name', 'English_score',
                                                    ' Math_score' ]
                    , index= [ 'a', 'b', 'c', 'd'] )
my_df

       name  English_score   Math_score
a  dongwook             50           86
b    sineui             89           31
c   ikjoong             68           91
d   yoonsoo             88           75

In [6]:
type(my_df)

pandas.core.frame.DataFrame

In [7]:
my_df.columns

Index(['name', 'English_score', ' Math_score'], dtype='object')

In [8]:
my_df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [11]:
my_df.dtypes

name             object
English_score     int64
 Math_score       int64
dtype: object

In [12]:
# index_col = 0 첫번째 칼럼의 데이터 값을 열(row)로 밀어주는 것

In [17]:
iphone_df = pd.read_csv('iphone.csv', index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [20]:
iphone_df.loc['iPhone 8', '메모리']

'2GB'

In [23]:
iphone_df.loc['iPhone X', :]

출시일        2017-11-03
디스플레이             5.8
메모리               3GB
출시 버전        iOS 11.1
Face ID           Yes
Name: iPhone X, dtype: object

In [24]:
iphone_df.loc['iPhone X']

출시일        2017-11-03
디스플레이             5.8
메모리               3GB
출시 버전        iOS 11.1
Face ID           Yes
Name: iPhone X, dtype: object

In [25]:
type(iphone_df.loc['iPhone X'])

pandas.core.series.Series

In [26]:
iphone_df.loc[:, '출시일']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [27]:
iphone_df['출시일']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [28]:
type(iphone_df['출시일'])

pandas.core.series.Series