In [1]:
import pandas as pd

In [2]:
two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], 
                       ['yoonsoo', 88, 75]]

In [3]:
my_df = pd.DataFrame(two_dimensional_list, columns=['name', 'English_score',
                                                    ' Math_score' ]
                    , index= [ 'a', 'b', 'c', 'd'] )
my_df

       name  English_score   Math_score
a  dongwook             50           86
b    sineui             89           31
c   ikjoong             68           91
d   yoonsoo             88           75

In [4]:
type(my_df)

pandas.core.frame.DataFrame

In [5]:
my_df.columns

Index(['name', 'English_score', ' Math_score'], dtype='object')

In [6]:
my_df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
my_df.dtypes

name             object
English_score     int64
 Math_score       int64
dtype: object

In [8]:
# index_col = 0 첫번째 칼럼의 데이터 값을 열(row)로 밀어주는 것

In [9]:
iphone_df = pd.read_csv('excel/iphone.csv', index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [10]:
iphone_df.loc['iPhone 8', '메모리']

'2GB'

In [11]:
iphone_df.loc['iPhone X', :]

출시일        2017-11-03
디스플레이             5.8
메모리               3GB
출시 버전        iOS 11.1
Face ID           Yes
Name: iPhone X, dtype: object

In [12]:
iphone_df.loc['iPhone X']

출시일        2017-11-03
디스플레이             5.8
메모리               3GB
출시 버전        iOS 11.1
Face ID           Yes
Name: iPhone X, dtype: object

In [13]:
type(iphone_df.loc['iPhone X'])

pandas.core.series.Series

In [14]:
iphone_df.loc[:, '출시일']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [15]:
iphone_df['출시일']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [16]:
type(iphone_df['출시일'])

pandas.core.series.Series

In [17]:
# 행 추출 
iphone_df.loc['iPhone X']

출시일        2017-11-03
디스플레이             5.8
메모리               3GB
출시 버전        iOS 11.1
Face ID           Yes
Name: iPhone X, dtype: object

In [18]:
iphone_df.loc[['iPhone X', 'iPhone 8']]

                 출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No

In [19]:
# 2차원이기 때문에 DataFrame 으로 나옴 
type(iphone_df.loc[['iPhone X', 'iPhone 8']])

pandas.core.frame.DataFrame

In [20]:
# 열 추출  
iphone_df['Face ID']

iPhone 7          No
iPhone 7 Plus     No
iPhone 8          No
iPhone 8 Plus     No
iPhone X         Yes
iPhone XS        Yes
iPhone XS Max    Yes
Name: Face ID, dtype: object

In [21]:
iphone_df[['Face ID', '출시일', '메모리']]

              Face ID         출시일  메모리
iPhone 7           No  2016-09-16  2GB
iPhone 7 Plus      No  2016-09-16  3GB
iPhone 8           No  2017-09-22  2GB
iPhone 8 Plus      No  2017-09-22  3GB
iPhone X          Yes  2017-11-03  3GB
iPhone XS         Yes  2018-09-21  4GB
iPhone XS Max     Yes  2018-09-21  4GB

In [22]:
# 데이터 프라임 슬라이싱 
iphone_df.loc['iPhone 8' : 'iPhone XS']

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

In [23]:
# 열을 중심으로 한 슬라이싱
iphone_df.loc[:, '메모리' : 'Face ID']

               메모리     출시 버전 Face ID
iPhone 7       2GB  iOS 10.0      No
iPhone 7 Plus  3GB  iOS 10.0      No
iPhone 8       2GB  iOS 11.0      No
iPhone 8 Plus  3GB  iOS 11.0      No
iPhone X       3GB  iOS 11.1     Yes
iPhone XS      4GB  iOS 12.0     Yes
iPhone XS Max  4GB  iOS 12.0     Yes

In [24]:
# 행과 열 모두 슬라이싱
iphone_df.loc['iPhone 7' : 'iPhone X', '메모리' : 'Face ID']

               메모리     출시 버전 Face ID
iPhone 7       2GB  iOS 10.0      No
iPhone 7 Plus  3GB  iOS 10.0      No
iPhone 8       2GB  iOS 11.0      No
iPhone 8 Plus  3GB  iOS 11.0      No
iPhone X       3GB  iOS 11.1     Yes

In [25]:
# 불린 리스트를 통해 필터링 하기: 생략하고 싶은 리스트를 False로 처리하면 된다.(개수에 맞게 리스트 요소를 모두 적으면 됨.)
iphone_df.loc[[True, False, True, True, False, True, False]]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

In [26]:
iphone_df['디스플레이'] > 5

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: 디스플레이, dtype: bool

In [27]:
# 조건을 걸어서 필터링 하기 
iphone_df.loc[iphone_df['디스플레이'] > 5]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [28]:
iphone_df['Face ID' ] == 'Yes'

iPhone 7         False
iPhone 7 Plus    False
iPhone 8         False
iPhone 8 Plus    False
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: Face ID, dtype: bool

In [29]:
iphone_df.loc[iphone_df['Face ID' ] == 'Yes']

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [30]:
# 조건을 2개 이상 걸기 
condition = (iphone_df['디스플레이'] > 5) | (iphone_df['Face ID' ] == 'Yes')

In [31]:
iphone_df[condition]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [32]:
# 특정 범위의 데이터를 확인 할 때 
# iloc[n : m] : n번째 부터 m번 이전까지 데이터를 추출 (index location)
iphone_df.iloc[2, 4]

'No'

In [33]:
iphone_df.iloc[[1, 3], [1, 4]]

               디스플레이 Face ID
iPhone 7 Plus    5.5      No
iPhone 8 Plus    5.5      No

In [34]:
iphone_df.iloc[3: , 1:4]

               디스플레이  메모리     출시 버전
iPhone 8 Plus    5.5  3GB  iOS 11.0
iPhone X         5.8  3GB  iOS 11.1
iPhone XS        5.8  4GB  iOS 12.0
iPhone XS Max    6.5  4GB  iOS 12.0

In [35]:
# DataFrame에 지정된 값에 새로운 값을 지정해주기 
iphone_df.loc['iPhone 8', '메모리']

'2GB'

In [36]:
iphone_df.loc['iPhone 8', '메모리'] = '2.5GB'
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [37]:
iphone_df.loc['iPhone 8', '출시 버전'] = 'iOS 10.3'
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  iOS 10.3      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [38]:
# 데이터 프레임의 열 삭제 
# iphone_df = iphone_df.drop('출시버전', axis = 1)

In [39]:
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  iOS 10.3      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [40]:
# 데이터 프레임의 한 행의 값을 모두 수정하기 
iphone_df.loc ['iPhone 8'] = ['2016-09-22', '4.7', '2GB', 'iOS 11.0', 'No']
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16   5.5  3GB  iOS 10.0      No
iPhone 8       2016-09-22   4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22   5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     Yes

In [41]:
iphone_df['디스플레이']

iPhone 7         4.7
iPhone 7 Plus    5.5
iPhone 8         4.7
iPhone 8 Plus    5.5
iPhone X         5.8
iPhone XS        5.8
iPhone XS Max    6.5
Name: 디스플레이, dtype: object

In [42]:
# 데이터 프레임의 한 열의 값을 모두 수정하기 
iphone_df['디스플레이'] = ['4.7 in', '5.5 in', '4.7 in', '5.5 in', '5.8 in', '5.8 in', '5.8 in']
iphone_df

                      출시일   디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16  4.7 in  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16  5.5 in  3GB  iOS 10.0      No
iPhone 8       2016-09-22  4.7 in  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22  5.5 in  3GB  iOS 11.0      No
iPhone X       2017-11-03  5.8 in  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21  5.8 in  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21  5.8 in  4GB  iOS 12.0     Yes

In [43]:
# 두 개 이상의 열의 값을 변경해주기 
#`iphone_df[['디스플레이', 'Face ID']] = 'x'` 
#`iphone_df`

In [44]:
# 두 개 이상의 행의 값을 변경해주기 
# iphone_df.loc[['iPhone 7', 'iPhone X']] = 'o'
# iphone_df

In [45]:
# 데이터 프레임에 새로운 행 추가하기 
iphone_df.loc['iPhone XR'] = ['2018-10-26', '6.1 in', '3GB', 'iOS 12.0.1', 'Yes']
iphone_df

                      출시일   디스플레이  메모리       출시 버전 Face ID
iPhone 7       2016-09-16  4.7 in  2GB    iOS 10.0      No
iPhone 7 Plus  2016-09-16  5.5 in  3GB    iOS 10.0      No
iPhone 8       2016-09-22  4.7 in  2GB    iOS 11.0      No
iPhone 8 Plus  2017-09-22  5.5 in  3GB    iOS 11.0      No
iPhone X       2017-11-03  5.8 in  3GB    iOS 11.1     Yes
iPhone XS      2018-09-21  5.8 in  4GB    iOS 12.0     Yes
iPhone XS Max  2018-09-21  5.8 in  4GB    iOS 12.0     Yes
iPhone XR      2018-10-26  6.1 in  3GB  iOS 12.0.1     Yes

In [46]:
# 데이터 프레임에 새로운 열(파생변수) 추가하기 
iphone_df['제조사'] = 'Apple'
iphone_df

                      출시일   디스플레이  메모리       출시 버전 Face ID    제조사
iPhone 7       2016-09-16  4.7 in  2GB    iOS 10.0      No  Apple
iPhone 7 Plus  2016-09-16  5.5 in  3GB    iOS 10.0      No  Apple
iPhone 8       2016-09-22  4.7 in  2GB    iOS 11.0      No  Apple
iPhone 8 Plus  2017-09-22  5.5 in  3GB    iOS 11.0      No  Apple
iPhone X       2017-11-03  5.8 in  3GB    iOS 11.1     Yes  Apple
iPhone XS      2018-09-21  5.8 in  4GB    iOS 12.0     Yes  Apple
iPhone XS Max  2018-09-21  5.8 in  4GB    iOS 12.0     Yes  Apple
iPhone XR      2018-10-26  6.1 in  3GB  iOS 12.0.1     Yes  Apple

In [47]:
# 데이터 프레임에 들어있는 행의 값 삭제하기 
# inplce=False : 기존의 데이터 프레임을 건들지 않는다는 의미 -> 즉 새로운 데이터 프레임을 만든다는 의미이다. 
# inplace=True : 기존의 데이터 프레임에다가 다음과 같은 정보를 반영함 
# iphone_df.drop('iPhone XR', axis='index', inplace=False)

In [48]:
iphone_df.drop('iPhone XR', axis='index', inplace=True)
iphone_df

                      출시일   디스플레이  메모리     출시 버전 Face ID    제조사
iPhone 7       2016-09-16  4.7 in  2GB  iOS 10.0      No  Apple
iPhone 7 Plus  2016-09-16  5.5 in  3GB  iOS 10.0      No  Apple
iPhone 8       2016-09-22  4.7 in  2GB  iOS 11.0      No  Apple
iPhone 8 Plus  2017-09-22  5.5 in  3GB  iOS 11.0      No  Apple
iPhone X       2017-11-03  5.8 in  3GB  iOS 11.1     Yes  Apple
iPhone XS      2018-09-21  5.8 in  4GB  iOS 12.0     Yes  Apple
iPhone XS Max  2018-09-21  5.8 in  4GB  iOS 12.0     Yes  Apple

In [49]:
iphone_df.drop('제조사', axis='columns', inplace=True)
iphone_df

                      출시일   디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16  4.7 in  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16  5.5 in  3GB  iOS 10.0      No
iPhone 8       2016-09-22  4.7 in  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22  5.5 in  3GB  iOS 11.0      No
iPhone X       2017-11-03  5.8 in  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21  5.8 in  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21  5.8 in  4GB  iOS 12.0     Yes

In [50]:
# 여러가지 행의 값 지우기 
iphone_df.drop(['iPhone 7', 'iPhone 8', 'iPhone X'], axis='index', inplace=True)
iphone_df

                      출시일   디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16  5.5 in  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22  5.5 in  3GB  iOS 11.0      No
iPhone XS      2018-09-21  5.8 in  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21  5.8 in  4GB  iOS 12.0     Yes

In [51]:
# index들의 이름 지어주는 방법
iphone_df.index.name = 'iPhone Series'
iphone_df

                      출시일   디스플레이  메모리     출시 버전 Face ID
iPhone Series
iPhone 7 Plus  2016-09-16  5.5 in  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22  5.5 in  3GB  iOS 11.0      No
iPhone XS      2018-09-21  5.8 in  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21  5.8 in  4GB  iOS 12.0     Yes

In [52]:
# index 자체를 바꾸는 법 
# iphone_df.set_index('바꾸고 싶은 인덱스 이름', inplace=True)

In [53]:
laptops_df = pd.read_csv('excel/laptops.csv')

In [54]:
laptops_df

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
0,Dell,Inspiron 15-3567,4,hdd,1024,15.6,40000,intel,i5,2.5,intel,NaN,linux,2.50,NaN
1,Apple,MacBook Air,8,ssd,128,13.3,55499,intel,i5,1.8,intel,2.0,mac,1.35,NaN
2,Apple,MacBook Air,8,ssd,256,13.3,71500,intel,i5,1.8,intel,2.0,mac,1.35,NaN
3,Apple,MacBook Pro,8,ssd,128,13.3,96890,intel,i5,2.3,intel,2.0,mac,3.02,NaN
4,Apple,MacBook Pro,8,ssd,256,13.3,112666,intel,i5,2.3,intel,2.0,mac,3.02,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,Asus,A555LF,8,hdd,1024,15.6,39961,intel,i3 4th gen,1.7,nvidia,2.0,windows,2.30,NaN
163,Asus,X555LA-XX172D,4,hdd,500,15.6,28489,intel,i3 4th gen,1.9,intel,NaN,linux,2.30,NaN
164,Asus,X554LD,2,hdd,500,15.6,29199,intel,i3 4th gen,1.9,intel,1.0,linux,2.30,NaN
165,Asus,X550LAV-XX771D,2,hdd,500,15.6,29990,intel,i3 4th gen,1.7,intel,NaN,linux,2.50,NaN
166,Asus,X540LA-XX538T,4,hdd,1024,15.6,30899,intel,i3 5th gen,2.0,intel,NaN,windows,2.30,NaN

In [55]:
# 상위 데이터 n개를 추출: .head
laptops_df.head(3)

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
0,Dell,Inspiron 15-3567,4,hdd,1024,15.6,40000,intel,i5,2.5,intel,NaN,linux,2.50,NaN
1,Apple,MacBook Air,8,ssd,128,13.3,55499,intel,i5,1.8,intel,2.0,mac,1.35,NaN
2,Apple,MacBook Air,8,ssd,256,13.3,71500,intel,i5,1.8,intel,2.0,mac,1.35,NaN

In [56]:
# 하위 데이터 n개를 추출: .head
laptops_df.tail(3)

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
164,Asus,X554LD,2,hdd,500,15.6,29199,intel,i3 4th gen,1.9,intel,1.0,linux,2.3,NaN
165,Asus,X550LAV-XX771D,2,hdd,500,15.6,29990,intel,i3 4th gen,1.7,intel,NaN,linux,2.5,NaN
166,Asus,X540LA-XX538T,4,hdd,1024,15.6,30899,intel,i3 5th gen,2.0,intel,NaN,windows,2.3,NaN

In [57]:
laptops_df.shape

(167, 15)

In [58]:
# 데이터의 열의 특징 파악(특성)
laptops_df.columns

Index(['brand', 'model', 'ram', 'hd_type', 'hd_size', 'screen_size', 'price',
       'processor_brand', 'processor_model', 'clock_speed',
       'graphic_card_brand', 'graphic_card_size', 'os', 'weight', 'comments'],
      dtype='object')

In [59]:
# 데이터의 정보 파악
laptops_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brand               167 non-null    object
 1   model               167 non-null    object
 2   ram                 167 non-null    int64
 3   hd_type             167 non-null    object
 4   hd_size             167 non-null    int64
 5   screen_size         167 non-null    float64
 6   price               167 non-null    int64
 7   processor_brand     167 non-null    object
 8   processor_model     167 non-null    object
 9   clock_speed         166 non-null    float64
 10  graphic_card_brand  163 non-null    object
 11  graphic_card_size   81 non-null     float64
 12  os                  167 non-null    object
 13  weight              160 non-null    float64
 14  comments            55 non-null     object
dtypes: float64(4), int64(3), object(8)
memory usage: 19.7+ KB

In [60]:
# 각 데이터의 기초통계량 제공
laptops_df.describe()

,ram,hd_size,screen_size,price,clock_speed,graphic_card_size,weight
count,167.000000,167.00000,167.000000,167.000000,166.000000,81.000000,160.000000
mean,6.898204,768.91018,14.775210,64132.898204,2.321084,52.160494,2.250813
std,3.787479,392.99080,1.376526,42797.674010,0.554187,444.134142,0.648446
min,2.000000,32.00000,10.100000,13872.000000,1.100000,1.000000,0.780000
25%,4.000000,500.00000,14.000000,35457.500000,1.900000,2.000000,1.900000
50%,8.000000,1024.00000,15.600000,47990.000000,2.300000,2.000000,2.200000
75%,8.000000,1024.00000,15.600000,77494.500000,2.600000,4.000000,2.600000
max,16.000000,2048.00000,17.600000,226000.000000,3.800000,4000.000000,4.200000

In [61]:
# 하나의 변수를 중심으로 데이터를 분류 
# ascending=False (내림차순, 숫자가 큰 수부터 정렬)
# ascending=True (오름차순, 숫자가 작은 수부터 정렬)
laptops_df.sort_values(by='price', ascending=False)

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
5,Apple,MacBook Pro (TouchBar),16,ssd,512,15.0,226000,intel,i7,2.70,intel,2.0,mac,2.5,NaN
90,Alienware,15 Notebook,16,hdd,1024,15.6,199000,intel,i7,2.60,nvidia,8.0,windows,3.5,Maximum Display Resolution : 1920 x 1080 pixel
96,Alienware,AW13R3-7000SLV-PUS,8,ssd,256,13.3,190256,intel,i7,3.00,nvidia,6.0,windows,2.6,13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31,Acer,Predator 17,16,ssd,256,17.3,178912,intel,i7,2.60,nvidia,NaN,windows,4.2,Integrated Graphics
154,Microsoft,Surface Book CR9-00013,8,ssd,128,13.5,178799,intel,i5,1.80,intel,NaN,windows,1.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Acer,Aspire ES1-523,4,hdd,1024,15.6,19465,amd,A4-7210,1.80,amd,NaN,linux,2.4,NaN
100,Acer,A315-31-P4CRUN.GNTSI.002,4,hdd,500,15.6,18990,intel,pentium,1.10,intel,NaN,windows,NaN,NaN
108,Acer,Aspire ES-15 NX.GKYSI.010,4,hdd,500,15.6,17990,amd,A4-7210,1.80,amd,NaN,windows,2.4,NaN
83,Acer,A315-31CDC UN.GNTSI.001,2,ssd,500,15.6,17990,intel,Celeron,1.10,intel,NaN,windows,2.1,NaN
148,Acer,Aspire SW3-016,2,ssd,32,10.1,13872,intel,Atom Z8300,1.44,intel,NaN,windows,1.2,NaN

In [62]:
laptops_df

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
0,Dell,Inspiron 15-3567,4,hdd,1024,15.6,40000,intel,i5,2.5,intel,NaN,linux,2.50,NaN
1,Apple,MacBook Air,8,ssd,128,13.3,55499,intel,i5,1.8,intel,2.0,mac,1.35,NaN
2,Apple,MacBook Air,8,ssd,256,13.3,71500,intel,i5,1.8,intel,2.0,mac,1.35,NaN
3,Apple,MacBook Pro,8,ssd,128,13.3,96890,intel,i5,2.3,intel,2.0,mac,3.02,NaN
4,Apple,MacBook Pro,8,ssd,256,13.3,112666,intel,i5,2.3,intel,2.0,mac,3.02,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,Asus,A555LF,8,hdd,1024,15.6,39961,intel,i3 4th gen,1.7,nvidia,2.0,windows,2.30,NaN
163,Asus,X555LA-XX172D,4,hdd,500,15.6,28489,intel,i3 4th gen,1.9,intel,NaN,linux,2.30,NaN
164,Asus,X554LD,2,hdd,500,15.6,29199,intel,i3 4th gen,1.9,intel,1.0,linux,2.30,NaN
165,Asus,X550LAV-XX771D,2,hdd,500,15.6,29990,intel,i3 4th gen,1.7,intel,NaN,linux,2.50,NaN
166,Asus,X540LA-XX538T,4,hdd,1024,15.6,30899,intel,i3 5th gen,2.0,intel,NaN,windows,2.30,NaN

In [63]:
laptops_df['brand']

0       Dell
1      Apple
2      Apple
3      Apple
4      Apple
       ...
162     Asus
163     Asus
164     Asus
165     Asus
166     Asus
Name: brand, Length: 167, dtype: object

In [64]:
# 문자데이터 항목 확인 (인자 확인)
laptops_df['brand'].unique()

array(['Dell', 'Apple', 'Acer', 'HP', 'Lenovo', 'Alienware', 'Microsoft',
       'Asus'], dtype=object)

In [65]:
# 문자데이터 빈도수 확인
laptops_df['brand'].value_counts()

brand
HP           55
Acer         35
Dell         31
Lenovo       18
Asus          9
Apple         7
Alienware     6
Microsoft     6
Name: count, dtype: int64

In [66]:
# 문자형 데이터의 기초통계량 확인
laptops_df['brand'].describe()

count     167
unique      8
top        HP
freq       55
Name: brand, dtype: object