In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('museum_1.csv')
df

             시설명  어른관람료      운영기관전화번호
0     필암서원 유물전시관    500  061-390-7224
1        원주역사박물관      0  033-737-4371
2        뮤지엄산미술관  15000  033-730-9000
3      오랜미래신화미술관      0  033-746-5256
4    연세대학교 원주박물관      0  033-760-2731
..           ...    ...           ...
895        함양박물관      0  055-960-5532
896         박물관수   5000  053-744-5500
897    대구은행금융박물관      0  053-740-2061
898      국립대구박물관      0  053-768-6051
899    증평민속체험박물관      0  043-835-4161

[900 rows x 3 columns]

## 과제 설명: 한국에서 잘나가는 동양예술전문가 솔희는 최근 "박물관이 살아 있다" 프로젝트를 시작했습니다.
 
"박물관이 살아 있다" 프로젝트는 점점 떨어져가는 문화예술공간의 방문율을 높이기 위해 시작되었습니다.  
김솔희씨는 먼저 예술의 흥행을 위해선 젊은이들의 참여가 시급하다고 판단하여, 대학교 박물관을 먼저 개선하기로 하였습니다.  

대학 박물관을 개선하기 위해 다음과 같이 박물관을 분류하기로 하였습니다.  

박물관은 대학/일반 박물관으로 나뉜다.  
시설명에 '대학'이 포함되어 있으면 '대학', 그렇지 않으면 '일반'으로 나누어 '분류' column에 입력한다.  
'분류' column을 만들어서 솔희를 도와주세요!

In [3]:
def func1(x):
    if '대학' in x: 
        return '대학'
    else: 
        return '일반'

df['분류'] = df['시설명'].apply(func1)

In [4]:
df

             시설명  어른관람료      운영기관전화번호  분류
0     필암서원 유물전시관    500  061-390-7224  일반
1        원주역사박물관      0  033-737-4371  일반
2        뮤지엄산미술관  15000  033-730-9000  일반
3      오랜미래신화미술관      0  033-746-5256  일반
4    연세대학교 원주박물관      0  033-760-2731  대학
..           ...    ...           ...  ..
895        함양박물관      0  055-960-5532  일반
896         박물관수   5000  053-744-5500  일반
897    대구은행금융박물관      0  053-740-2061  일반
898      국립대구박물관      0  053-768-6051  일반
899    증평민속체험박물관      0  043-835-4161  일반

[900 rows x 4 columns]

In [5]:
# 또 다른 방법 

# is_university = df['시설명'].str.contains('대학')
# df.loc[is_university == True, '분류'] = '대학'
# df.loc[is_university == False, '분류'] = '일반'

## 다음 목표: 

### 한국에서 잘나가는 동양예술전문가 솔희는 최근 "박물관이 살아 있다" 프로젝트를 시작했습니다.
 
솔희는 어느 지역에 박물관이 많은지 분석해 보려고 합니다.

하지만 주어진 데이터에는 주소가 없네요.
그러던 도중, 전화번호 앞자리가 지역을 나타낸다는 것을 깨달았습니다.

솔희가 박물관의 위치를 파악할 수 있게 '운영기관전화번호' column의 맨 앞 3자리를 추출하고, '지역번호' column에 넣어주세요.

In [6]:
# -를 기준으로 문자열을 나누고 싶다면, pat='-' 옵션을 사용
df['운영기관전화번호'].str.split(pat='-', n=3, expand=True)

       0    1     2
0    061  390  7224
1    033  737  4371
2    033  730  9000
3    033  746  5256
4    033  760  2731
..   ...  ...   ...
895  055  960  5532
896  053  744  5500
897  053  740  2061
898  053  768  6051
899  043  835  4161

[900 rows x 3 columns]

In [7]:
region_number = df['운영기관전화번호'].str.split(pat='-', n=3, expand=True)

In [8]:
df['지역번호'] = region_number[0]
df

             시설명  어른관람료      운영기관전화번호  분류 지역번호
0     필암서원 유물전시관    500  061-390-7224  일반  061
1        원주역사박물관      0  033-737-4371  일반  033
2        뮤지엄산미술관  15000  033-730-9000  일반  033
3      오랜미래신화미술관      0  033-746-5256  일반  033
4    연세대학교 원주박물관      0  033-760-2731  대학  033
..           ...    ...           ...  ..  ...
895        함양박물관      0  055-960-5532  일반  055
896         박물관수   5000  053-744-5500  일반  053
897    대구은행금융박물관      0  053-740-2061  일반  053
898      국립대구박물관      0  053-768-6051  일반  053
899    증평민속체험박물관      0  043-835-4161  일반  043

[900 rows x 5 columns]

## 다음 목표: 

### 한국에서 잘나가는 동양예술전문가 솔희는 최근 "박물관이 살아 있다" 프로젝트를 시작했습니다.
 
솔희는 지역번호를 이용해서 지역 정보를 알아내고자 합니다.  

지역번호가 02이면 '서울시'이고, 지역번호가 064라면 '제주도'입니다.  

'지역번호' column을 '지역명' 으로 변경하고, 아래 규칙에 따라 지역을 넣어주세요.  

지역명	전화번호
서울시	02    
경기도	031, 032  
강원도	033  
충청도	041, 042, 043, 044  
부산시	051  
경상도	052, 053, 054, 055  
전라도	061, 062, 063  
제주도	064  
기타	1577, 070   
파이썬 사전(dictionary)을 만드는 과정이 번거로울 수 있지만, 실제 분석 상황을 가정한 과제입니다. 직접 작성해 보세요!

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시설명       900 non-null    object
 1   어른관람료     900 non-null    int64
 2   운영기관전화번호  900 non-null    object
 3   분류        900 non-null    object
 4   지역번호      900 non-null    object
dtypes: int64(1), object(4)
memory usage: 35.3+ KB

In [10]:
region = {
    '02': '서울시',
    '031': '경기도', '032': '경기도',
    '033': '강원도', 
    '041': '충청도', '042': '충청도', '043': '충청도', '044': '충청도',
    '051': '부산시', 
    '052': '경상도', '053': '경상도', '054': '경상도', '055': '경상도',
    '061': '전라도', '062': '전라도', '063': '전라도',
    '064': '제주도',
    '1577': '기타', '070': '기타'
}

In [11]:
df["지역번호"] = df["지역번호"].map(region)

In [12]:
df.rename(columns={"지역번호": "지역명"}, inplace=True)

In [13]:
df

             시설명  어른관람료      운영기관전화번호  분류  지역명
0     필암서원 유물전시관    500  061-390-7224  일반  전라도
1        원주역사박물관      0  033-737-4371  일반  강원도
2        뮤지엄산미술관  15000  033-730-9000  일반  강원도
3      오랜미래신화미술관      0  033-746-5256  일반  강원도
4    연세대학교 원주박물관      0  033-760-2731  대학  강원도
..           ...    ...           ...  ..  ...
895        함양박물관      0  055-960-5532  일반  경상도
896         박물관수   5000  053-744-5500  일반  경상도
897    대구은행금융박물관      0  053-740-2061  일반  경상도
898      국립대구박물관      0  053-768-6051  일반  경상도
899    증평민속체험박물관      0  043-835-4161  일반  충청도

[900 rows x 5 columns]

## 다음 목표: 

### 한국에서 잘나가는 동양예술전문가 솔희는 최근 "박물관이 살아 있다" 프로젝트를 시작했습니다.
 
파이썬 사전과 .map()을 사용해서 지역명을 알아낸 솔희는, 조금 더 편한 방법을 고민하고 있습니다.

고민하던 중, '지역번호와 지역명에 대한 데이터는 누군가 이미 만들어두지 않았을까'라는 생각을 하게 되는데요.

인터넷에서 지역번호와 지역명이 있는 데이터 region_number.csv를 구했습니다!

이 데이터를 먼저 살펴보고, .merge() 메소드를 활용해서 museum_3.csv에 '지역명' column을 추가해 보세요.  

(새로운 데이터 프레임 사용)

In [15]:
museum = pd.read_csv("museum_3.csv", dtype={'지역번호': str})
number = pd.read_csv("region_number.csv", dtype={'지역번호': str})

In [16]:
museum

             시설명  어른관람료      운영기관전화번호  분류 지역번호
0     필암서원 유물전시관    500  061-390-7224  일반  061
1        원주역사박물관      0  033-737-4371  일반  033
2        뮤지엄산미술관  15000  033-730-9000  일반  033
3      오랜미래신화미술관      0  033-746-5256  일반  033
4    연세대학교 원주박물관      0  033-760-2731  대학  033
..           ...    ...           ...  ..  ...
895        함양박물관      0  055-960-5532  일반  055
896         박물관수   5000  053-744-5500  일반  053
897    대구은행금융박물관      0  053-740-2061  일반  053
898      국립대구박물관      0  053-768-6051  일반  053
899    증평민속체험박물관      0  043-835-4161  일반  043

[900 rows x 5 columns]

In [17]:
number

    지역번호      지역명
0     02    서울특별시
1    031      경기도
2    032    인천광역시
3    033      강원도
4    041     충청남도
5    042    대전광역시
6    043     충청북도
7    044  세종특별자치시
8    051    부산광역시
9    052    울산광역시
10   053    대구광역시
11   054     경상북도
12   055     경상남도
13   061     전라남도
14   062    광주광역시
15   063     전라북도
16   064  제주특별자치도
17   070    인터넷전화
18  1577     기타번호

In [20]:
# how='left'로 설정해야 박물관 순서가 유지될 수 있음
pd.merge(museum, number, on='지역번호', how='left')

             시설명  어른관람료      운영기관전화번호  분류 지역번호    지역명
0     필암서원 유물전시관    500  061-390-7224  일반  061   전라남도
1        원주역사박물관      0  033-737-4371  일반  033    강원도
2        뮤지엄산미술관  15000  033-730-9000  일반  033    강원도
3      오랜미래신화미술관      0  033-746-5256  일반  033    강원도
4    연세대학교 원주박물관      0  033-760-2731  대학  033    강원도
..           ...    ...           ...  ..  ...    ...
895        함양박물관      0  055-960-5532  일반  055   경상남도
896         박물관수   5000  053-744-5500  일반  053  대구광역시
897    대구은행금융박물관      0  053-740-2061  일반  053  대구광역시
898      국립대구박물관      0  053-768-6051  일반  053  대구광역시
899    증평민속체험박물관      0  043-835-4161  일반  043   충청북도

[900 rows x 6 columns]